version: '4'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:18
    working_dir: /usr/src/node_clean_arch
    restart: always
    command: bash -c "npm install --omit=dev && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongo:27017/node_clean_arch
    volumes:
      - ./dist/:/usr/src/node_clean_arch/dist/
      - ./package.json:/usr/src/node_clean_arch/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
    